// src/lib/inbox/thread.service.ts

export interface Attachment {
  id: string;
  filename: string;
  mimeType: string;
  size: number;
}

export interface MessageItem {
  id: string;
  snippet: string;
  sender: { name: string; email: string };
  recipient: { name: string; email: string };
  date: string;
  bodyHtml: string;
  bodyText: string;
  attachments: Attachment[];
}

export interface JobThread {
  id: string;
  subject: string;
  messages: MessageItem[];
  lastMessageDate: string;
  isUnread: boolean;
  isStarred: boolean;
  snippet: string;
  labels: string[];
  smartStatus?: string; // determined by AI later
  summary?: string; // generated by AI later
  privateNotes?: string;
}

function parseContact(headerValue: string) {
  // e.g. "John Doe <john@doe.com>" or "john@doe.com"
  const match = headerValue.match(/(.*)<(.+)>/);
  if (match) {
    return { name: match[1].replace(/"/g, '').trim(), email: match[2].trim() };
  }
  return { name: headerValue, email: headerValue };
}

function getHeader(headers: any[], name: string): string {
  const h = headers.find((h) => h.name.toLowerCase() === name.toLowerCase());
  return h ? h.value : '';
}

function parseMessagePart(part: any, msg: any) {
  if (part.mimeType === 'text/plain') {
    if (part.body.data) {
      msg.bodyText += decodeURIComponent(escape(atob(part.body.data.replace(/-/g, '+').replace(/_/g, '/'))));
    }
  } else if (part.mimeType === 'text/html') {
    if (part.body.data) {
      msg.bodyHtml += decodeURIComponent(escape(atob(part.body.data.replace(/-/g, '+').replace(/_/g, '/'))));
    }
  } else if (part.filename && part.filename.length > 0) {
    msg.attachments.push({
      id: part.body.attachmentId,
      filename: part.filename,
      mimeType: part.mimeType,
      size: part.body.size
    });
  }

  if (part.parts) {
    part.parts.forEach((p: any) => parseMessagePart(p, msg));
  }
}

export function parseGmailThread(rawThread: any): JobThread {
  const messages: MessageItem[] = [];
  let threadSubject = 'No Subject';
  let isUnread = false;
  let isStarred = false;
  let allLabels = new Set<string>();

  rawThread.messages.forEach((rawMsg: any) => {
    const headers = rawMsg.payload.headers;
    const subject = getHeader(headers, 'subject');
    if (subject && threadSubject === 'No Subject') threadSubject = subject;

    const from = parseContact(getHeader(headers, 'from'));
    const to = parseContact(getHeader(headers, 'to'));
    const date = getHeader(headers, 'date');

    if (rawMsg.labelIds) {
      rawMsg.labelIds.forEach((l: string) => {
        allLabels.add(l);
        if (l === 'UNREAD') isUnread = true;
        if (l === 'STARRED') isStarred = true;
      });
    }

    const msg: MessageItem = {
      id: rawMsg.id,
      snippet: rawMsg.snippet,
      sender: from,
      recipient: to,
      date: new Date(date || parseInt(rawMsg.internalDate)).toISOString(),
      bodyHtml: '',
      bodyText: '',
      attachments: []
    };

    // Parse body
    if (rawMsg.payload.parts) {
      rawMsg.payload.parts.forEach((p: any) => parseMessagePart(p, msg));
    } else {
      parseMessagePart(rawMsg.payload, msg); // flat body
    }

    messages.push(msg);
  });

  // Sort messages by date (oldest first)
  messages.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  const lastMessage = messages[messages.length - 1];

  return {
    id: rawThread.id,
    subject: threadSubject,
    messages,
    lastMessageDate: lastMessage ? lastMessage.date : new Date().toISOString(),
    isUnread,
    isStarred,
    snippet: lastMessage ? lastMessage.snippet : '',
    labels: Array.from(allLabels)
  };
}
